Repository jshstar/ticket-auction-backend, pull requests merged in 2024-01, with the labels that each got.

#26 #25- [init - exception] 공통으로 사용할 exception handler 및 exception class 구현
  src/main/java/com/sparta/ticketauction/global/exception/ApiException.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/java/com/sparta/ticketauction/global/exception/GlobalExceptionHandler.java
Labels: 🎉 init

#35 #8 [goods] Entity 및 Request 초기 설정
  src/main/java/com/sparta/ticketauction/domain/admin/request/GoodsRequest.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/AgeGrade.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/Goods.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/GoodsCategory.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/GoodsImage.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/ImageType.java
  src/main/java/com/sparta/ticketauction/domain/goods/repository/GoodsCategoryRepository.java
  src/main/java/com/sparta/ticketauction/domain/goods/repository/GoodsImageRepository.java
Labels: 🎉 init

#37 #8 [goods] Entity 수정
  src/main/java/com/sparta/ticketauction/domain/goods/entity/Goods.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/GoodsCategory.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/GoodsImage.java
Labels: 🩹 fix

#38 #27 [sequence] Entity 및 Request 수정
  src/main/java/com/sparta/ticketauction/domain/sequence/entity/Sequence.java
  src/main/java/com/sparta/ticketauction/domain/sequence/repository/SequenceRepository.java
  src/main/java/com/sparta/ticketauction/domain/sequence/request/SequenceRequest.java
  src/main/java/com/sparta/ticketauction/domain/sequence/service/SequenceService.java
  src/main/java/com/sparta/ticketauction/domain/sequence/service/SequenceServiceImpl.java
Labels: 🎉 init

#36 #22 [user] 회원 request/response 에 final 키워드 첨가
  src/main/java/com/sparta/ticketauction/domain/user/entity/User.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserCreateRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserInfoUpdateRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserPasswordUpdateRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/response/UserResponse.java
Labels: 🩹 fix

#39 #8 [goods] goods Entity 수정
  src/main/java/com/sparta/ticketauction/domain/admin/request/GoodsRequest.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/Goods.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/GoodsCategory.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/GoodsImage.java
Labels: ✨ update

#40 #22 [user] request에서 생년월일 입력하는 거 추가함
  src/main/java/com/sparta/ticketauction/domain/user/request/UserCreateRequest.java
Labels: 🩹 fix

#42 #23 [auction] 경매 도메인 설계
  src/main/java/com/sparta/ticketauction/domain/auction/entity/Auction.java
  src/main/java/com/sparta/ticketauction/domain/auction/entity/Bid.java
  src/main/java/com/sparta/ticketauction/domain/auction/request/AuctionCreateRequest.java
Labels: 🎉 init

#41 #22 - [user] entity 생년월일 컬럼이 빠져서 다시 추가함
  src/main/java/com/sparta/ticketauction/domain/user/entity/User.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserCreateRequest.java
Labels: 🩹 fix

#44 #24 [init-reservation] 예매 도메인 구현
  src/main/java/com/sparta/ticketauction/domain/reservation/entity/Reservation.java
  src/main/java/com/sparta/ticketauction/domain/reservation/entity/ReservationStatus.java
Labels: 🎉 init

#43 #28 [places] places Entity 초기 설정
  src/main/java/com/sparta/ticketauction/domain/admin/request/PlacesRequest.java
  src/main/java/com/sparta/ticketauction/domain/admin/request/PlacesSeatInfo.java
  src/main/java/com/sparta/ticketauction/domain/places/entity/Places.java
  src/main/java/com/sparta/ticketauction/domain/places/repository/PlacesRepository.java
  src/main/java/com/sparta/ticketauction/domain/places/service/PlacesServiceImpl.java
Labels: 🎉 init

#46 #45 [exception] 예외처리 핸들러 추가 구현
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/java/com/sparta/ticketauction/global/exception/GlobalExceptionHandler.java
Labels: ✨ update

#48 #23 [auction] 경매 추가 요청 DTO 유효성 검증 수정
  src/main/java/com/sparta/ticketauction/domain/auction/request/AuctionCreateRequest.java
Labels: 🐛 bugfix

#49 #28 [place] Entity 및 Request 수정
  src/main/java/com/sparta/ticketauction/domain/admin/request/GoodsRequest.java
  src/main/java/com/sparta/ticketauction/domain/admin/request/PlaceRequest.java
  src/main/java/com/sparta/ticketauction/domain/admin/request/PlaceSeatInfo.java
  src/main/java/com/sparta/ticketauction/domain/admin/request/PlacesRequest.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/AgeGrade.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/Goods.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/GoodsCategory.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/GoodsImage.java
  src/main/java/com/sparta/ticketauction/domain/place/controller/PlaceController.java
  src/main/java/com/sparta/ticketauction/domain/place/entity/Place.java
  src/main/java/com/sparta/ticketauction/domain/place/repository/PlaceRepository.java
  src/main/java/com/sparta/ticketauction/domain/place/service/PlaceService.java
  src/main/java/com/sparta/ticketauction/domain/place/service/PlaceServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/places/repository/PlacesRepository.java
  src/main/java/com/sparta/ticketauction/domain/places/service/PlacesService.java
  src/main/java/com/sparta/ticketauction/domain/seat/entity/Seat.java
  src/main/java/com/sparta/ticketauction/domain/seat/request/SeatRequest.java
Labels: 🩹 fix, 🚚 move

#50 #1 [user] 회원 가입 기능 서비스 로직/테스트 구현
  src/main/java/com/sparta/ticketauction/domain/user/controller/UserController.java
  src/main/java/com/sparta/ticketauction/domain/user/entity/User.java
  src/main/java/com/sparta/ticketauction/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserService.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/config/PasswordEncoderConfig.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/test/java/com/sparta/ticketauction/domain/user/service/UserServiceImplTest.java
Labels: ✨ update, 🎉 init, 🍻 test

#51 #27 [sequence] Sequence Entity 및 Request message 수정
  src/main/java/com/sparta/ticketauction/domain/sequence/entity/Sequence.java
  src/main/java/com/sparta/ticketauction/domain/sequence/request/SequenceRequest.java
Labels: 🩹 fix

#52 #1 [user] UserCreateRequest 검증 테스트 구현
  src/main/java/com/sparta/ticketauction/domain/user/request/UserCreateRequest.java
  src/test/java/com/sparta/ticketauction/domain/user/UserUtil.java
  src/test/java/com/sparta/ticketauction/domain/user/request/UserCreateRequestTest.java
  src/test/java/com/sparta/ticketauction/domain/user/service/UserServiceImplTest.java
Labels: 🍻 test

#54 #53 [successCode] 코드 합병 시, 충돌을 최소화하기 위한 마지막 코드 추가
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
Labels: ✨ update

#58 #8 [goods] Entity 수정
  src/main/java/com/sparta/ticketauction/domain/goods/entity/GoodsImage.java
Labels: 🐛 bugfix

#59 #22 [user] 회원 엔티티 내의 포인트 충전, 사용 코드 추가
  src/main/java/com/sparta/ticketauction/domain/user/entity/User.java
Labels: ✨ update

#60 #22 [user] 회원 엔티티에 `is_deleted` 컬럼 추가/BaseEntity 상속
  src/main/java/com/sparta/ticketauction/domain/user/entity/User.java
  src/main/java/com/sparta/ticketauction/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserServiceImpl.java
  src/test/java/com/sparta/ticketauction/domain/user/service/UserServiceImplTest.java
Labels: ✨ update

#64 #62 [global] Redis 환경 구성 및 유틸 구현
  build.gradle
  src/main/java/com/sparta/ticketauction/global/annotaion/DistributedLock.java
  src/main/java/com/sparta/ticketauction/global/aop/AopForTransaction.java
  src/main/java/com/sparta/ticketauction/global/aop/DistributedLockAop.java
  src/main/java/com/sparta/ticketauction/global/config/RedissonConfig.java
  src/main/java/com/sparta/ticketauction/global/util/CustomSpringELParser.java
  src/main/java/com/sparta/ticketauction/global/util/RedissonUtils.java
Labels: 🎉 init

#67 #66 [bugfix-reservation] Reservation -> GoodsSequenceSeat 복합키 매핑 오류 수정
  src/main/java/com/sparta/ticketauction/domain/reservation/entity/Reservation.java
Labels: 🐛 bugfix

#68 #31 [goods_sequence_seat] 생성자 수정
  src/main/java/com/sparta/ticketauction/domain/goods_sequence_seat/entity/GoodsSequenceSeat.java
Labels: 🐛 bugfix

#65 #63 [global] s3 환경 구성
  build.gradle
  src/main/java/com/sparta/ticketauction/global/config/S3Config.java
  src/main/java/com/sparta/ticketauction/global/util/S3Uploader.java
Labels: 🎉 init

#72 #69 [refactor-domain] Request 및 Entity 구조 변경
  src/main/java/com/sparta/ticketauction/domain/admin/request/GoodsRequest.java
  src/main/java/com/sparta/ticketauction/domain/admin/request/GoodsSequenceSeatRequest.java
  src/main/java/com/sparta/ticketauction/domain/admin/request/PlaceRequest.java
  src/main/java/com/sparta/ticketauction/domain/admin/request/PlaceSeatAuctionInfo.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/Goods.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/GoodsCategory.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/GoodsImage.java
  src/main/java/com/sparta/ticketauction/domain/goods_sequence_seat/entity/GoodsSequenceSeat.java
  src/main/java/com/sparta/ticketauction/domain/place/entity/Place.java
  src/main/java/com/sparta/ticketauction/domain/seat/entity/Seat.java
  src/main/java/com/sparta/ticketauction/domain/seat/request/SeatRequest.java
  src/main/java/com/sparta/ticketauction/domain/sequence/entity/Sequence.java
  src/main/java/com/sparta/ticketauction/domain/sequence/request/SequenceRequest.java
Labels: ♻️ refactor

#74 #73 [auction] 경매 도메인 수정
  src/main/java/com/sparta/ticketauction/domain/auction/entity/Auction.java
  src/main/java/com/sparta/ticketauction/domain/auction/entity/Bid.java
  src/main/java/com/sparta/ticketauction/domain/auction/request/AuctionCreateRequest.java
  src/main/java/com/sparta/ticketauction/domain/auction/request/BidRequest.java
Labels: ♻️ refactor, 🩹 fix

#70 #15 [user] 로그인 기능 구현
  build.gradle
  src/main/java/com/sparta/ticketauction/domain/user/entity/constant/Role.java
  src/main/java/com/sparta/ticketauction/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserLoginRequest.java
  src/main/java/com/sparta/ticketauction/global/config/PasswordEncoderConfig.java
  src/main/java/com/sparta/ticketauction/global/config/RedisConfig.java
  src/main/java/com/sparta/ticketauction/global/config/RedissonConfig.java
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/main/java/com/sparta/ticketauction/global/security/UserDetailsImpl.java
  src/main/java/com/sparta/ticketauction/global/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/util/LettuceUtils.java
Labels: ✨ update, 🩹 fix, 🎉 init, 🐻gradle

#75 #15 [user] 로그인 통합 테스트 작성
  src/main/resources/application-test.yml
  src/test/java/com/sparta/ticketauction/domain/user/AuthControllerTest.java
  src/test/java/com/sparta/ticketauction/domain/user/JwtAuthenticationHelper.java
Labels: 🍻 test

#76 #69 [user] 정적 팩토리 메서드 패턴에서 빌드 패턴으로 리팩토링
  src/main/java/com/sparta/ticketauction/domain/user/entity/User.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserCreateRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserServiceImpl.java
  src/test/java/com/sparta/ticketauction/domain/user/service/UserServiceImplTest.java
Labels: ♻️ refactor

#78 #77 [gradle] jwt/redis 관련 의존성 추가
  build.gradle
Labels: 🐻gradle

#80 #79 [redis] Redis 관련 설정 수정
  src/main/java/com/sparta/ticketauction/global/config/RedisConfig.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
  src/main/java/com/sparta/ticketauction/global/util/LettuceUtils.java
Labels: 🩹 fix

#82 #15 [user] jwt 관련 코드 수정
  src/main/java/com/sparta/ticketauction/domain/user/entity/User.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
  src/main/java/com/sparta/ticketauction/global/util/LettuceUtils.java
  src/test/java/com/sparta/ticketauction/domain/user/AuthControllerTest.java
Labels: 🩹 fix

#84 #19 [reservation] 좌석 예매 API 추가
  src/main/java/com/sparta/ticketauction/domain/goods/repository/GoodsImageRepository.java
  src/main/java/com/sparta/ticketauction/domain/goods/repository/GoodsRepository.java
  src/main/java/com/sparta/ticketauction/domain/reservation/controller/ReservationController.java
  src/main/java/com/sparta/ticketauction/domain/reservation/entity/Reservation.java
  src/main/java/com/sparta/ticketauction/domain/reservation/request/ReservationCreateRequest.java
  src/main/java/com/sparta/ticketauction/domain/reservation/response/ReservationDetailResponse.java
  src/main/java/com/sparta/ticketauction/domain/reservation/service/ReservationService.java
  src/main/java/com/sparta/ticketauction/domain/reservation/service/ReservationServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/seat/repository/SeatRepository.java
  src/main/java/com/sparta/ticketauction/domain/sequence/repository/SequenceRepository.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/test/java/com/sparta/ticketauction/domain/reservation/ReservationUtil.java
  src/test/java/com/sparta/ticketauction/domain/reservation/service/ReservationServiceImplTest.java
Labels: ✨ update, 🍻 test

#86 #71 [user] 인증 유저 객체를 가져오는 annotation 구현
  src/main/java/com/sparta/ticketauction/global/annotaion/CurrentUser.java
Labels: 🎉 init

#85 #83 [user] 로그아웃 기능 구현
  build.gradle
  src/main/java/com/sparta/ticketauction/domain/user/controller/AuthController.java
  src/main/java/com/sparta/ticketauction/domain/user/service/AuthService.java
  src/main/java/com/sparta/ticketauction/domain/user/service/AuthServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/main/java/com/sparta/ticketauction/global/util/LettuceUtils.java
  src/test/java/com/sparta/ticketauction/domain/user/controller/AuthControllerTest.java
  src/test/java/com/sparta/ticketauction/domain/user/request/UserCreateRequestTest.java
  src/test/java/com/sparta/ticketauction/domain/user/service/AuthServiceImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/service/UserServiceImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/util/JwtAuthenticationHelper.java
  src/test/java/com/sparta/ticketauction/domain/user/util/UserUtil.java
Labels: ✨ update, 🎉 init, 🚚 move, 🍻 test, 🐻gradle

#87 #19 [reservation] 좌석 예매 생성 DTO 유효성 검증 테스트 추가 및 회차-공연 fetch join 쿼리 오류 수정
  src/main/java/com/sparta/ticketauction/domain/goods/entity/GoodsImage.java
  src/main/java/com/sparta/ticketauction/domain/sequence/repository/SequenceRepository.java
  src/test/java/com/sparta/ticketauction/domain/reservation/request/ReservationCreateRequestTest.java
  src/test/java/com/sparta/ticketauction/domain/reservation/service/ReservationServiceImplTest.java
Labels: 🐛 bugfix, 🍻 test

#88 #56 [admin] 공연장 추가 API 기능 구현 및 테스트, DTO 검증 테스트
  src/main/java/com/sparta/ticketauction/domain/admin/controller/AdminController.java
  src/main/java/com/sparta/ticketauction/domain/admin/request/PlaceRequest.java
  src/main/java/com/sparta/ticketauction/domain/admin/response/PlaceResponse.java
  src/main/java/com/sparta/ticketauction/domain/admin/service/AdminService.java
  src/main/java/com/sparta/ticketauction/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/place/entity/Place.java
  src/main/java/com/sparta/ticketauction/domain/place/service/PlaceServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/seat/entity/Seat.java
  src/main/java/com/sparta/ticketauction/domain/seat/request/SeatRequest.java
  src/main/java/com/sparta/ticketauction/domain/seat/service/SeatServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/user/response/UserResponse.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/main/resources/application.yml
  src/test/java/com/sparta/ticketauction/domain/admin/request/PlaceRequestTest.java
  src/test/java/com/sparta/ticketauction/domain/admin/request/SeatRequestTest.java
  src/test/java/com/sparta/ticketauction/domain/admin/service/AdminServiceTest.java
Labels: 🐛 bugfix, ✨ update, 🩹 fix

#92 #15 [user] 인증/인가 관련 기능 수정
  src/main/java/com/sparta/ticketauction/domain/user/entity/User.java
  src/main/java/com/sparta/ticketauction/domain/user/service/AuthServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/java/com/sparta/ticketauction/global/jwt/ExceptionHandlerFilter.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
  src/test/java/com/sparta/ticketauction/domain/user/util/JwtAuthenticationHelper.java
Labels: ♻️ refactor, 🩹 fix, 🚚 move

#91 #89 [admin user] 관리자 유저 관련 기능 구현
  src/main/java/com/sparta/ticketauction/domain/user/entity/User.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserCreateRequest.java
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/ticketauction/global/exception/AccessDeniedHandlerImpl.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/sparta/ticketauction/domain/reservation/service/ReservationServiceImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/controller/AuthControllerTest.java
  src/test/java/com/sparta/ticketauction/domain/user/request/UserCreateRequestTest.java
  src/test/java/com/sparta/ticketauction/domain/user/service/UserServiceImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/util/JwtAuthenticationHelper.java
  src/test/java/com/sparta/ticketauction/domain/user/util/UserUtil.java
Labels: ♻️ refactor, 🎉 init, 🚚 move, 🐻gradle

#95 #16 [user] 회원 가입 시, 휴대폰 번호 인증 구현
  build.gradle
  src/main/java/com/sparta/ticketauction/domain/user/controller/AuthController.java
  src/main/java/com/sparta/ticketauction/domain/user/entity/User.java
  src/main/java/com/sparta/ticketauction/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/ticketauction/domain/user/request/SmsMessageRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserCreateRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserForVerificationRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/response/SmsResponse.java
  src/main/java/com/sparta/ticketauction/domain/user/service/AuthService.java
  src/main/java/com/sparta/ticketauction/domain/user/service/AuthServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserService.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/main/java/com/sparta/ticketauction/global/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/util/LettuceUtils.java
  src/main/resources/application.yml
  src/test/java/com/sparta/ticketauction/domain/user/request/UserCreateRequestTest.java
  src/test/java/com/sparta/ticketauction/domain/user/service/AuthServiceImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/service/UserServiceImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/util/UserUtil.java
Labels: 🐛 bugfix, ✨ update, 🩹 fix, 🎉 init, 🍻 test, 🐻gradle

#90 #14 [auction] 입찰하기 기능 구현
  src/main/java/com/sparta/ticketauction/domain/auction/constant/AuctionConstant.java
  src/main/java/com/sparta/ticketauction/domain/auction/controller/BidController.java
  src/main/java/com/sparta/ticketauction/domain/auction/repository/AuctionRedissonRepository.java
  src/main/java/com/sparta/ticketauction/domain/auction/service/BidService.java
  src/main/java/com/sparta/ticketauction/domain/auction/service/BidServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/ticketauction/global/annotaion/DistributedLock.java
  src/main/java/com/sparta/ticketauction/global/aop/AopForTransaction.java
  src/main/java/com/sparta/ticketauction/global/aop/DistributedLockAop.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/main/resources/application.yml
  src/test/java/com/sparta/ticketauction/domain/auction/service/BidServiceTest.java
Labels: ✨ update

#98 #57 [admin] 공연 추가 API 기능 구현 및 테스트
  src/main/java/com/sparta/ticketauction/domain/admin/controller/AdminController.java
  src/main/java/com/sparta/ticketauction/domain/admin/request/GoodsRequest.java
  src/main/java/com/sparta/ticketauction/domain/admin/service/AdminService.java
  src/main/java/com/sparta/ticketauction/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/Goods.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/GoodsImage.java
  src/main/java/com/sparta/ticketauction/domain/goods/repository/GoodsCategoryRepository.java
  src/main/java/com/sparta/ticketauction/domain/goods/service/GoodsServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/goods_sequence_seat/service/GoodsSequenceSeatServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/place/service/PlaceServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/sequence/service/SequenceServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/main/java/com/sparta/ticketauction/global/util/S3Uploader.java
  src/test/java/com/sparta/ticketauction/domain/admin/request/GoodsRequestTest.java
  src/test/java/com/sparta/ticketauction/domain/admin/service/AdminServiceTest.java
Labels: ♻️ refactor, ✨ update, 🩹 fix, 🚚 move

#102 #99 [입찰] 입찰 도메인 수정
  src/main/java/com/sparta/ticketauction/domain/auction/repository/AuctionRedissonRepository.java
  src/main/java/com/sparta/ticketauction/domain/auction/service/BidServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/bid/constant/BidConstant.java
  src/main/java/com/sparta/ticketauction/domain/bid/controller/BidController.java
  src/main/java/com/sparta/ticketauction/domain/bid/entity/Bid.java
  src/main/java/com/sparta/ticketauction/domain/bid/repository/BidRepository.java
  src/main/java/com/sparta/ticketauction/domain/bid/request/BidRequest.java
  src/main/java/com/sparta/ticketauction/domain/bid/service/BidService.java
Labels: 🩹 fix, 🚚 move, 🔥 del

#100 #97 [user] 토큰 재발급 기능 구현
  src/main/java/com/sparta/ticketauction/domain/user/controller/AuthController.java
  src/main/java/com/sparta/ticketauction/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/ticketauction/domain/user/service/AuthService.java
  src/main/java/com/sparta/ticketauction/domain/user/service/AuthServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserService.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/java/com/sparta/ticketauction/global/jwt/ExceptionHandlerFilter.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/main/resources/application-test.yml
  src/test/java/com/sparta/ticketauction/domain/user/controller/AuthControllerTest.java
  src/test/java/com/sparta/ticketauction/domain/user/service/AuthServiceImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/util/JwtAuthenticationHelper.java
Labels: 🐛 bugfix, ✨ update, 🩹 fix, 🍻 test

#108 #107 [입찰] 입찰하기 기능 N + 1 문제 리팩토링
  src/main/java/com/sparta/ticketauction/domain/bid/repository/BidRepository.java
  src/main/java/com/sparta/ticketauction/domain/bid/service/BidServiceImpl.java
Labels: ♻️ refactor

#111 #109 [경매] 경매 종료 API 구현
  src/main/java/com/sparta/ticketauction/domain/auction/entity/Auction.java
  src/main/java/com/sparta/ticketauction/domain/auction/eventlistner/AuctionEventListener.java
  src/main/java/com/sparta/ticketauction/domain/auction/service/AuctionService.java
  src/main/java/com/sparta/ticketauction/domain/auction/service/AuctionServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/event/AuctionEndEvent.java
  src/test/java/com/sparta/ticketauction/domain/auction/service/AuctionServiceTest.java
Labels: ✨ update, 🎉 init

#112 #110 [경매] 경매 등록 API 구현
  src/main/java/com/sparta/ticketauction/domain/auction/entity/Auction.java
  src/main/java/com/sparta/ticketauction/domain/auction/service/AuctionServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/bid/service/BidService.java
  src/test/java/com/sparta/ticketauction/domain/auction/service/AuctionServiceTest.java
Labels: 🐛 bugfix, ✨ update

#114 #113 [user] request/response 리팩토링
  src/main/java/com/sparta/ticketauction/domain/user/controller/AuthController.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserForVerificationRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/request/sms/SmsMessageRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/request/sms/UserForVerificationRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/response/SmsResponse.java
  src/main/java/com/sparta/ticketauction/domain/user/response/UserResponse.java
  src/main/java/com/sparta/ticketauction/domain/user/service/AuthService.java
  src/main/java/com/sparta/ticketauction/domain/user/service/AuthServiceImpl.java
  src/test/java/com/sparta/ticketauction/domain/user/service/AuthServiceImplTest.java
Labels: ♻️ refactor, 🚚 move

#126 #122 [등급] 도메인 추가
  src/main/java/com/sparta/ticketauction/domain/seat/entity/Grade.java
Labels: 🎉 init

#128 #10 [user] 유저 전화번호, 닉네임 수정 기능 구현
  build.gradle
  src/main/java/com/sparta/ticketauction/domain/user/controller/UserController.java
  src/main/java/com/sparta/ticketauction/domain/user/entity/User.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserCreateRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserInfoUpdateRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserLoginRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserNicknameUpdateRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserPhoneUpdateRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/request/sms/UserForVerificationRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/service/AuthService.java
  src/main/java/com/sparta/ticketauction/domain/user/service/AuthServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserService.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/test/java/com/sparta/ticketauction/domain/user/service/AuthServiceImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/service/UserServiceImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/util/UserUtil.java
Labels: ✨ update, 🍻 test

#132 #9 [user] 회원 정보 조회 기능 구현
  src/main/java/com/sparta/ticketauction/domain/user/controller/UserController.java
  src/main/java/com/sparta/ticketauction/domain/user/response/UserResponse.java
  src/main/java/com/sparta/ticketauction/domain/user/service/AuthServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserService.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/test/java/com/sparta/ticketauction/domain/user/service/AuthServiceImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/service/UserServiceImplTest.java
Labels: ♻️ refactor, ✨ update, 🩹 fix, 🍻 test

#140 #10 [user] 유저 정보 수정 API 변경
  src/main/java/com/sparta/ticketauction/domain/user/controller/UserController.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserNicknameUpdateRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserUpdateRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserService.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/test/java/com/sparta/ticketauction/domain/user/service/UserServiceImplTest.java
Labels: 🩹 fix, 🍻 test

#141 #11 [user] 회원 비밀번호 변경 기능 구현
  src/main/java/com/sparta/ticketauction/domain/user/controller/UserController.java
  src/main/java/com/sparta/ticketauction/domain/user/entity/User.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserPasswordUpdateRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserService.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/test/java/com/sparta/ticketauction/domain/user/service/UserServiceImplTest.java
Labels: ✨ update, 🍻 test

#143 #103 [point] 포인트 변동 로그 구현
  src/main/java/com/sparta/ticketauction/domain/user/entity/Point.java
  src/main/java/com/sparta/ticketauction/domain/user/entity/User.java
  src/main/java/com/sparta/ticketauction/domain/user/enums/PointType.java
  src/main/java/com/sparta/ticketauction/domain/user/enums/Role.java
  src/main/java/com/sparta/ticketauction/domain/user/repository/PointRepository.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserCreateRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/service/AuthServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/user/service/PointService.java
  src/main/java/com/sparta/ticketauction/domain/user/service/PointServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
  src/test/java/com/sparta/ticketauction/domain/user/service/AuthServiceImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/service/PointServiceImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/util/UserUtil.java
Labels: ✨ update, 🎉 init, 🍻 test

#142 #135 [admin] 공연장 생성 추가 API 구현 및 테스트 코드 작성
  src/main/java/com/sparta/ticketauction/domain/admin/controller/AdminController.java
  src/main/java/com/sparta/ticketauction/domain/admin/service/AdminService.java
  src/main/java/com/sparta/ticketauction/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/GoodsInfo.java
  src/main/java/com/sparta/ticketauction/domain/goods/repository/GoodsImageRepository.java
  src/main/java/com/sparta/ticketauction/domain/place/service/PlaceService.java
  src/main/java/com/sparta/ticketauction/domain/place/service/PlaceServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/place/service/ZoneService.java
  src/main/java/com/sparta/ticketauction/domain/place/service/ZoneServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/schedule/entity/Schedule.java
  src/main/java/com/sparta/ticketauction/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/sparta/ticketauction/domain/schedule/request/ScheduleRequest.java
  src/main/java/com/sparta/ticketauction/domain/schedule/service/ScheduleService.java
  src/main/java/com/sparta/ticketauction/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/seat/entity/AuctionSeat.java
  src/main/java/com/sparta/ticketauction/domain/sequence/repository/SequenceRepository.java
  src/main/java/com/sparta/ticketauction/domain/sequence/service/SequenceService.java
  src/main/java/com/sparta/ticketauction/domain/sequence/service/SequenceServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/test/java/com/sparta/ticketauction/domain/admin/request/PlaceRequestTest.java
  src/test/java/com/sparta/ticketauction/domain/admin/service/AdminServiceTest.java
Labels: ✨ update, 🩹 fix, 🎉 init, 🍻 test

#146 #136 [admin] 공연 생성 API 기능 구현 및 테스트 추가
  src/main/java/com/sparta/ticketauction/domain/admin/controller/AdminController.java
  src/main/java/com/sparta/ticketauction/domain/admin/request/GoodsRequest.java
  src/main/java/com/sparta/ticketauction/domain/admin/response/GoodsResponse.java
  src/main/java/com/sparta/ticketauction/domain/admin/service/AdminService.java
  src/main/java/com/sparta/ticketauction/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/goods/repository/GoodsRepository.java
  src/main/java/com/sparta/ticketauction/domain/goods/service/GoodsInfoService.java
  src/main/java/com/sparta/ticketauction/domain/goods/service/GoodsInfoServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/goods/service/GoodsService.java
  src/main/java/com/sparta/ticketauction/domain/goods/service/GoodsServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/place/dto/ZoneInfo.java
  src/main/java/com/sparta/ticketauction/domain/place/service/PlaceService.java
  src/main/java/com/sparta/ticketauction/domain/place/service/PlaceServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/schedule/service/ScheduleService.java
  src/main/java/com/sparta/ticketauction/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/test/java/com/sparta/ticketauction/domain/admin/request/GoodsRequestTest.java
  src/test/java/com/sparta/ticketauction/domain/admin/service/AdminServiceTest.java
Labels: ✨ update, 🩹 fix, 🎉 init, 🍻 test

#149 #12 [user] 회원탈퇴 기능 구현
  src/main/java/com/sparta/ticketauction/domain/user/controller/UserController.java
  src/main/java/com/sparta/ticketauction/domain/user/entity/User.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserService.java
  src/main/java/com/sparta/ticketauction/domain/user/service/impl/AuthServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/user/service/impl/PointServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/test/java/com/sparta/ticketauction/domain/user/controller/AuthControllerTest.java
  src/test/java/com/sparta/ticketauction/domain/user/service/AuthServiceImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/service/PointServiceImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/service/UserServiceImplTest.java
Labels: ✨ update, 🚚 move, 🍻 test

#147 #144 로그인 뷰 관련 구현
  build.gradle
  src/main/java/com/sparta/ticketauction/HomeController.java
  src/main/java/com/sparta/ticketauction/domain/user/controller/AuthController.java
  src/main/java/com/sparta/ticketauction/domain/user/controller/UserViewController.java
  src/main/java/com/sparta/ticketauction/domain/user/service/impl/AuthServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
  src/main/resources/static/css/login.css
  src/main/resources/static/css/style.css
  src/main/resources/static/images/email-icon.png
  src/main/resources/static/images/pw-icon.png
  src/main/resources/static/images/ticket.png
  src/main/resources/static/js/basic.js
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
Labels: ✨ update, 🩹 fix, 💄 style, 🐻gradle

#153 #125 [경매] 도메인 재 수정
  src/main/java/com/sparta/ticketauction/domain/auction/entity/Auction.java
  src/main/java/com/sparta/ticketauction/domain/auction/request/AuctionCreateRequest.java
  src/main/java/com/sparta/ticketauction/domain/auction/service/AuctionService.java
  src/main/java/com/sparta/ticketauction/domain/auction/service/AuctionServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/bid/service/BidServiceImpl.java
  src/test/java/com/sparta/ticketauction/domain/auction/request/AuctionCreateRequestTest.java
  src/test/java/com/sparta/ticketauction/domain/auction/service/AuctionServiceTest.java
Labels: ♻️ refactor, ✨ update, 🚚 move

#157 #156 [admin] 경매 생성 API 구현
  src/main/java/com/sparta/ticketauction/domain/admin/controller/AdminController.java
  src/main/java/com/sparta/ticketauction/domain/admin/response/ZoneGradeResponse.java
  src/main/java/com/sparta/ticketauction/domain/admin/service/AdminService.java
  src/main/java/com/sparta/ticketauction/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/test/java/com/sparta/ticketauction/domain/admin/request/ZoneGradeRequestTest.java
Labels: 🐛 bugfix, ✨ update, 🍻 test

#163 #125 [fix-auction] 예매 의존성 추가
  src/main/java/com/sparta/ticketauction/domain/auction/service/AuctionServiceImpl.java
  src/test/java/com/sparta/ticketauction/domain/auction/service/AuctionServiceTest.java
Labels: 🩹 fix

#167 #151 [payment] 토스 결제 API 연동 구현
  build.gradle
  src/main/java/com/sparta/ticketauction/HomeController.java
  src/main/java/com/sparta/ticketauction/domain/payment/controller/PaymentController.java
  src/main/java/com/sparta/ticketauction/domain/payment/entity/Payment.java
  src/main/java/com/sparta/ticketauction/domain/payment/repository/PaymentRepository.java
  src/main/java/com/sparta/ticketauction/domain/payment/request/PaymentFromUserRequest.java
  src/main/java/com/sparta/ticketauction/domain/payment/request/PaymentToApiRequest.java
  src/main/java/com/sparta/ticketauction/domain/payment/response/PaymentSuccessCardResponse.java
  src/main/java/com/sparta/ticketauction/domain/payment/response/PaymentSuccessResponse.java
  src/main/java/com/sparta/ticketauction/domain/payment/service/PaymentService.java
  src/main/java/com/sparta/ticketauction/domain/payment/service/PaymentServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/user/controller/UserViewController.java
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/static/css/payment.css
  src/main/resources/static/header.html
  src/main/resources/static/images/charge.png
  src/main/resources/static/index.html
  src/main/resources/static/js/basic.js
  src/main/resources/static/login.html
  src/main/resources/static/paymentFail.html
  src/main/resources/static/paymentRequest.html
  src/main/resources/static/paymentSuccess.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/test/java/com/sparta/ticketauction/domain/user/service/AuthServiceImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/service/PointServiceImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/util/JwtAuthenticationHelper.java
  src/test/java/com/sparta/ticketauction/domain/user/util/UserUtil.java
Labels: ✨ update, 🩹 fix, 🎉 init, 🚚 move, 🔥 del, 💄 style, 🐻gradle

#174 #171 [payment] 결제 후 처리 페이지 수정, js 리팩토링
  src/main/java/com/sparta/ticketauction/domain/payment/service/PaymentServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/user/controller/AuthController.java
  src/main/java/com/sparta/ticketauction/domain/user/service/AuthService.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserService.java
  src/main/java/com/sparta/ticketauction/domain/user/service/impl/AuthServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
  src/main/resources/static/css/payment.css
  src/main/resources/static/css/style.css
  src/main/resources/static/header.html
  src/main/resources/static/images/fireworks.png
  src/main/resources/static/js/basic.js
  src/main/resources/static/js/payment.js
  src/main/resources/static/paymentFail.html
  src/main/resources/static/paymentRequest.html
  src/main/resources/static/paymentSuccess.html
Labels: ♻️ refactor, ✨ update, 🩹 fix, 💄 style

#179 #178 [입찰] 입찰하기 입찰자 포인트 버그 수정
  src/main/java/com/sparta/ticketauction/domain/bid/service/BidServiceImpl.java
Labels: 🐛 bugfix

#180 #18 [경매] 경매 참가 API 구현
  src/main/java/com/sparta/ticketauction/domain/auction/controller/AuctionController.java
  src/main/java/com/sparta/ticketauction/domain/auction/response/AuctionInfoResponse.java
  src/main/java/com/sparta/ticketauction/domain/auction/service/AuctionService.java
  src/main/java/com/sparta/ticketauction/domain/auction/service/AuctionServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/bid/constant/BidConstant.java
  src/main/java/com/sparta/ticketauction/domain/bid/controller/BidController.java
  src/main/java/com/sparta/ticketauction/domain/bid/redis/RedisPublisher.java
  src/main/java/com/sparta/ticketauction/domain/bid/redis/RedisSubscriber.java
  src/main/java/com/sparta/ticketauction/domain/bid/repository/BidRedisRepository.java
  src/main/java/com/sparta/ticketauction/domain/bid/repository/SseRepository.java
  src/main/java/com/sparta/ticketauction/domain/bid/service/BidRedisService.java
  src/main/java/com/sparta/ticketauction/domain/bid/service/BidService.java
  src/main/java/com/sparta/ticketauction/domain/bid/service/BidServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/bid/service/SseService.java
  src/main/java/com/sparta/ticketauction/domain/bid/service/SseServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/config/RedisConfig.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/main/java/com/sparta/ticketauction/global/util/LettuceUtils.java
Labels: ✨ update

#181 #175 [ token] 프론트에서 토큰 재발급 요청
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
  src/main/resources/static/header.html
  src/main/resources/static/index.html
  src/main/resources/static/js/basic.js
  src/main/resources/static/js/token.js
  src/main/resources/static/login.html
  src/main/resources/static/paymentFail.html
  src/main/resources/static/paymentRequest.html
  src/main/resources/static/paymentSuccess.html
Labels: ✨ update, 🩹 fix, 🎉 init, 💄 style

#182 #176 [admin] 구조 변경으로 인한 각 도메인 리펙토링
  src/main/java/com/sparta/ticketauction/domain/admin/controller/AdminController.java
  src/main/java/com/sparta/ticketauction/domain/admin/request/GoodsCreateRequest.java
  src/main/java/com/sparta/ticketauction/domain/admin/request/GoodsInfoCreateRequest.java
  src/main/java/com/sparta/ticketauction/domain/admin/request/GradeCreateRequest.java
  src/main/java/com/sparta/ticketauction/domain/admin/request/PlaceCreateRequest.java
  src/main/java/com/sparta/ticketauction/domain/admin/request/ZoneGradeCreateRequest.java
  src/main/java/com/sparta/ticketauction/domain/admin/response/GoodsCreateResponse.java
  src/main/java/com/sparta/ticketauction/domain/admin/response/GoodsInfoCreateResponse.java
  src/main/java/com/sparta/ticketauction/domain/admin/response/GradeCreateResponse.java
  src/main/java/com/sparta/ticketauction/domain/admin/response/PlaceCreateResponse.java
  src/main/java/com/sparta/ticketauction/domain/admin/response/ZoneGradeCreateResponse.java
  src/main/java/com/sparta/ticketauction/domain/admin/service/AdminService.java
  src/main/java/com/sparta/ticketauction/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/Goods.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/GoodsInfo.java
  src/main/java/com/sparta/ticketauction/domain/goods/response/GoodsGetResponse.java
  src/main/java/com/sparta/ticketauction/domain/goods/response/GoodsInfoGetResponse.java
  src/main/java/com/sparta/ticketauction/domain/goods/service/GoodsInfoService.java
  src/main/java/com/sparta/ticketauction/domain/goods/service/GoodsInfoServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/goods/service/GoodsService.java
  src/main/java/com/sparta/ticketauction/domain/goods/service/GoodsServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/grade/service/GradeService.java
  src/main/java/com/sparta/ticketauction/domain/grade/service/GradeServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/grade/service/ZoneGradeService.java
  src/main/java/com/sparta/ticketauction/domain/grade/service/ZoneGradeServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/place/service/PlaceService.java
  src/main/java/com/sparta/ticketauction/domain/place/service/PlaceServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/test/java/com/sparta/ticketauction/domain/admin/request/GoodsCreateRequestTest.java
  src/test/java/com/sparta/ticketauction/domain/admin/request/GoodsInfoCreateRequestTest.java
  src/test/java/com/sparta/ticketauction/domain/admin/request/GoodsRequestTest.java
  src/test/java/com/sparta/ticketauction/domain/admin/request/GradeCreateRequestTest.java
  src/test/java/com/sparta/ticketauction/domain/admin/request/PlaceCreateRequestTest.java
  src/test/java/com/sparta/ticketauction/domain/admin/request/ZoneGradeCreateRequestTest.java
  src/test/java/com/sparta/ticketauction/domain/admin/service/AdminServiceTest.java
Labels: ♻️ refactor, 🩹 fix, 🍻 test

#189 #186 [입찰] 내 입찰 내역 조회 기능 구현
  build.gradle
  src/main/java/com/sparta/ticketauction/domain/auction/entity/Auction.java
  src/main/java/com/sparta/ticketauction/domain/bid/constant/BidStatus.java
  src/main/java/com/sparta/ticketauction/domain/bid/controller/BidController.java
  src/main/java/com/sparta/ticketauction/domain/bid/entity/Bid.java
  src/main/java/com/sparta/ticketauction/domain/bid/repository/BidRepository.java
  src/main/java/com/sparta/ticketauction/domain/bid/repository/BidRepositoryCustom.java
  src/main/java/com/sparta/ticketauction/domain/bid/repository/BidRepositoryCustomImpl.java
  src/main/java/com/sparta/ticketauction/domain/bid/response/BidInfoResponse.java
  src/main/java/com/sparta/ticketauction/domain/bid/service/BidService.java
  src/main/java/com/sparta/ticketauction/domain/bid/service/BidServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/config/QueryDslConfig.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/test/java/com/sparta/ticketauction/domain/bid/repository/BidRepositoryCustomImplTest.java
Labels: ♻️ refactor, ✨ update, 🎉 init

#192 #185 [user] 마이페이지 내 유저 관련 프론트 구현
  src/main/java/com/sparta/ticketauction/domain/user/controller/AuthController.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserUpdateRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/resources/static/css/mypage.css
  src/main/resources/static/header.html
  src/main/resources/static/js/mypage-menu.js
  src/main/resources/static/js/token.js
  src/main/resources/static/mypage-menu.html
  src/main/resources/static/update-password.html
  src/main/resources/static/update-user-info.html
  src/main/resources/static/user-info.html
Labels: ✨ update, 🩹 fix, 🎉 init, 💄 style

#193 #188 [goods] 공연 정보 입력 페이지 구현
  src/main/resources/static/css/goodsInfo.css
  src/main/resources/static/css/place.css
  src/main/resources/static/goodsInfo.html
  src/main/resources/static/js/admin.js
  src/main/resources/static/place.html
Labels: 💄 style

#199 #190 [point] 포인트 충전, 변동 내역 조회 프론트 구현 및 기능 수정
  src/main/java/com/sparta/ticketauction/domain/payment/service/PaymentServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/user/controller/PointController.java
  src/main/java/com/sparta/ticketauction/domain/user/entity/Point.java
  src/main/java/com/sparta/ticketauction/domain/user/entity/User.java
  src/main/java/com/sparta/ticketauction/domain/user/enums/PointType.java
  src/main/java/com/sparta/ticketauction/domain/user/repository/PointRepository.java
  src/main/java/com/sparta/ticketauction/domain/user/repository/PointRepositoryCustom.java
  src/main/java/com/sparta/ticketauction/domain/user/repository/PointRepositoryCustomImpl.java
  src/main/java/com/sparta/ticketauction/domain/user/response/PointChargeResponse.java
  src/main/java/com/sparta/ticketauction/domain/user/response/PointResponse.java
  src/main/java/com/sparta/ticketauction/domain/user/service/PointService.java
  src/main/java/com/sparta/ticketauction/domain/user/service/impl/PointServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/main/resources/application-test.yml
  src/main/resources/static/css/mypage.css
  src/main/resources/static/js/mypage-menu.js
  src/main/resources/static/mypage-menu.html
  src/main/resources/static/point-charge-list.html
  src/main/resources/static/point-list.html
  src/test/java/com/sparta/ticketauction/domain/user/repository/PointRepositoryCustomImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/service/AuthServiceImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/service/PointServiceImplTest.java
  src/test/java/com/sparta/ticketauction/domain/user/util/UserUtil.java
Labels: ♻️ refactor, ✨ update, 🩹 fix, 🎉 init, 🍻 test, 💄 style

#197 #194 [goods] 공연 추가 페이지 구현 및 gitignore 수정
  .gitignore
  src/main/java/com/sparta/ticketauction/domain/goods/controller/GoodsController.java
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
  src/main/resources/static/css/goods.css
  src/main/resources/static/css/goodsInfo.css
  src/main/resources/static/goods.html
  src/main/resources/static/goodsInfo.html
  src/main/resources/static/js/admin.js
  src/main/resources/static/place.html
Labels: 🙈 docs, 🩹 fix, 💄 style

#196 #195 [refactor-bid] 입찰하기 서비스 코드 리팩토링
  src/main/java/com/sparta/ticketauction/domain/auction/entity/Auction.java
  src/main/java/com/sparta/ticketauction/domain/bid/controller/BidController.java
  src/main/java/com/sparta/ticketauction/domain/bid/service/BidService.java
  src/main/java/com/sparta/ticketauction/domain/bid/service/BidServiceImpl.java
Labels: ♻️ refactor

#201 #200 [user] 회원탈퇴 프론트 구현
  src/main/java/com/sparta/ticketauction/domain/user/controller/UserController.java
  src/main/java/com/sparta/ticketauction/domain/user/request/UserDeleteRequest.java
  src/main/java/com/sparta/ticketauction/domain/user/service/UserService.java
  src/main/java/com/sparta/ticketauction/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/resources/static/header.html
  src/main/resources/static/js/common-menu.js
  src/main/resources/static/payment/fail.html
  src/main/resources/static/payment/request.html
  src/main/resources/static/payment/success.html
  src/main/resources/static/user/common-menu.html
  src/main/resources/static/user/info.html
  src/main/resources/static/user/signup.html
  src/main/resources/static/user/update-info.html
  src/main/resources/static/user/update-pw.html
  src/main/resources/static/user/withdraw.html
  src/test/java/com/sparta/ticketauction/domain/user/service/UserServiceImplTest.java
Labels: ♻️ refactor, 🩹 fix, 🎉 init, 🚚 move, 💄 style

#203 #198 [grade] 등급 추가 페이지 구현 및 공연장, 공연 추가 페이지 수정
  src/main/resources/static/css/goods.css
  src/main/resources/static/css/grade.css
  src/main/resources/static/css/place.css
  src/main/resources/static/goods.html
  src/main/resources/static/grade.html
  src/main/resources/static/js/admin.js
  src/main/resources/static/place.html
Labels: 🩹 fix, 💄 style

#208 #195 [입찰] 입찰 도메인 리팩토링
  src/main/java/com/sparta/ticketauction/domain/auction/entity/Auction.java
  src/main/java/com/sparta/ticketauction/domain/auction/request/AuctionCreateRequest.java
  src/main/java/com/sparta/ticketauction/domain/auction/response/AuctionDetailResponse.java
  src/main/java/com/sparta/ticketauction/domain/auction/service/AuctionServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/bid/controller/BidController.java
  src/main/java/com/sparta/ticketauction/domain/bid/repository/BidRedisRepository.java
  src/main/java/com/sparta/ticketauction/domain/bid/repository/BidRepositoryCustom.java
  src/main/java/com/sparta/ticketauction/domain/bid/repository/BidRepositoryCustomImpl.java
  src/main/java/com/sparta/ticketauction/domain/bid/service/BidRedisService.java
  src/main/java/com/sparta/ticketauction/domain/bid/service/BidService.java
  src/main/java/com/sparta/ticketauction/domain/bid/service/BidServiceImpl.java
  src/test/java/com/sparta/ticketauction/domain/auction/service/AuctionServiceTest.java
  src/test/java/com/sparta/ticketauction/domain/bid/service/BidServiceTest.java
Labels: ♻️ refactor

#209 #115 [reservation] 예약 API 추가 및 관련 DTO 추가
  build.gradle
  src/main/java/com/sparta/ticketauction/domain/grade/repository/ZoneGradeQueryRepository.java
  src/main/java/com/sparta/ticketauction/domain/grade/repository/ZoneGradeQueryRepositoryImpl.java
  src/main/java/com/sparta/ticketauction/domain/grade/repository/ZoneGradeRepository.java
  src/main/java/com/sparta/ticketauction/domain/grade/service/ZoneGradeService.java
  src/main/java/com/sparta/ticketauction/domain/grade/service/ZoneGradeServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/reservation/controller/ReservationController.java
  src/main/java/com/sparta/ticketauction/domain/reservation/dto/ReservationSeatInfo.java
  src/main/java/com/sparta/ticketauction/domain/reservation/entity/Reservation.java
  src/main/java/com/sparta/ticketauction/domain/reservation/entity/ReservationStatus.java
  src/main/java/com/sparta/ticketauction/domain/reservation/repository/ReservationQueryRepository.java
  src/main/java/com/sparta/ticketauction/domain/reservation/repository/ReservationQueryRepositoryImpl.java
  src/main/java/com/sparta/ticketauction/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/sparta/ticketauction/domain/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/sparta/ticketauction/domain/reservation/repository/ReservationRepositoryCustomImpl.java
  src/main/java/com/sparta/ticketauction/domain/reservation/request/ReservationCreateRequest.java
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/entity/ReservationSeat.java
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/entity/ReservationSeatId.java
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/repository/ReservationSeatQueryRepository.java
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/repository/ReservationSeatQueryRepositoryImpl.java
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/repository/ReservationSeatRepository.java
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/request/ReservationSeatCreateRequest.java
  src/main/java/com/sparta/ticketauction/domain/reservation/response/ReservationDetailResponse.java
  src/main/java/com/sparta/ticketauction/domain/reservation/response/ReservationResponse.java
  src/main/java/com/sparta/ticketauction/domain/reservation/service/ReservationService.java
  src/main/java/com/sparta/ticketauction/domain/reservation/service/ReservationServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/schedule/repository/ScheduleQueryRepository.java
  src/main/java/com/sparta/ticketauction/domain/schedule/repository/ScheduleQueryRepositoryImpl.java
  src/main/java/com/sparta/ticketauction/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/sparta/ticketauction/domain/schedule/service/ScheduleService.java
  src/main/java/com/sparta/ticketauction/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/config/QuerydslConfig.java
  src/main/java/com/sparta/ticketauction/global/config/RedisConfig.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/main/java/com/sparta/ticketauction/global/util/UrlUtil.java
Labels: ♻️ refactor, ✨ update, 🩹 fix, 🚚 move, 🔥 del, 🐻gradle

#210 #206 [data] 연령 등급 값, Open API를 이용해 데이터 가져오는 유틸 구현
  src/main/java/com/sparta/ticketauction/domain/goods/entity/AgeGrade.java
  src/main/java/com/sparta/ticketauction/global/util/dataUtil.java
Labels: 🎉 init

#211 #204 [goods] 공연 상세 조회 페이지 구현
  src/main/java/com/sparta/ticketauction/global/config/QuerydslConfig.java
  src/main/resources/static/css/goods-details.css
  src/main/resources/static/css/goods-info.css
  src/main/resources/static/css/grade.css
  src/main/resources/static/goods-details.html
  src/main/resources/static/goods-info.html
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/goods-details.js
  src/main/resources/static/place.html
Labels: 🩹 fix, 💄 style

#216 #202 [view] 메인페이지 구현, css 통일
  src/main/java/com/sparta/ticketauction/domain/payment/service/PaymentServiceImpl.java
  src/main/resources/static/css/goods-info.css
  src/main/resources/static/css/goods.css
  src/main/resources/static/css/grade.css
  src/main/resources/static/css/mypage.css
  src/main/resources/static/css/payment.css
  src/main/resources/static/css/place.css
  src/main/resources/static/css/style.css
  src/main/resources/static/css/user-input.css
  src/main/resources/static/goods-info.html
  src/main/resources/static/goods.html
  src/main/resources/static/grade.html
  src/main/resources/static/header.html
  src/main/resources/static/index.html
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/basic.js
  src/main/resources/static/js/goods.js
  src/main/resources/static/js/payment.js
  src/main/resources/static/js/token.js
  src/main/resources/static/login.html
  src/main/resources/static/payment/request.html
  src/main/resources/static/payment/success.html
  src/main/resources/static/place.html
  src/main/resources/static/user/common-menu.html
  src/main/resources/static/user/point-charge-list.html
  src/main/resources/static/user/point-list.html
  src/main/resources/static/user/signup.html
  src/main/resources/static/user/update-info.html
  src/main/resources/static/user/update-pw.html
  src/main/resources/static/user/withdraw.html
Labels: 🩹 fix, 💄 style

#218 #217 [url] local과 dev에 따라 달라지는 도메인 관련 코드 추가
  src/main/resources/static/css/goods-details.css
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/basic.js
  src/main/resources/static/js/common-menu.js
  src/main/resources/static/js/goods-details.js
  src/main/resources/static/js/goods.js
  src/main/resources/static/js/payment.js
  src/main/resources/static/js/signup.js
  src/main/resources/static/js/token.js
Labels: 🩹 fix

#220 #219 [view] 공연상세 조회 페이지
  src/main/resources/static/css/goods-details.css
  src/main/resources/static/css/zone-grade.css
  src/main/resources/static/goods-details.html
  src/main/resources/static/header.html
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/basic.js
  src/main/resources/static/js/goods-details.js
  src/main/resources/static/js/goods.js
  src/main/resources/static/login.html
  src/main/resources/static/zone-grade.html
Labels: ✨ update, 💄 style

#223 CI/CD Workflow 스크립트 작성
  .github/workflows/ci-test.yml
Labels: 🎉 init

#224 Create cicd.yml
  .github/workflows/cicd.yml
Labels: 🎉 init

#222 #215 [auction] 경매 생성 페이지 구현 및 AuctionCreateRequest 수정
  src/main/java/com/sparta/ticketauction/domain/admin/controller/AdminController.java
  src/main/java/com/sparta/ticketauction/domain/auction/request/AuctionCreateRequest.java
  src/main/java/com/sparta/ticketauction/domain/place/entity/Zone.java
  src/main/resources/static/auction.html
  src/main/resources/static/css/auction.css
  src/main/resources/static/js/admin.js
  src/main/resources/static/place.html
Labels: ✨ update, 🩹 fix, 💄 style

#230 Update cicd.yml
  .github/workflows/cicd.yml
Labels: 🩹 fix

#231 Create Dockerfile
  Dockerfile
Labels: 🎉 init

#232 Create appspec.yml
  appspec.yml
Labels: 🎉 init

#233 [global-security] Security Cors 임시 설정
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
Labels: ✨ update

#229 #173 [reserve-view] 좌석 예매 view 구현 및 관련 API, DTO, 설정 추가
  src/main/java/com/sparta/ticketauction/domain/auction/response/AuctionDetailResponse.java
  src/main/java/com/sparta/ticketauction/domain/auction/service/AuctionServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/bid/controller/BidController.java
  src/main/java/com/sparta/ticketauction/domain/goods/controller/GoodsController.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/Goods.java
  src/main/java/com/sparta/ticketauction/domain/goods/entity/GoodsInfo.java
  src/main/java/com/sparta/ticketauction/domain/goods/repository/GoodsRepository.java
  src/main/java/com/sparta/ticketauction/domain/goods/repository/GoodsRepositoryCustom.java
  src/main/java/com/sparta/ticketauction/domain/goods/repository/GoodsRepositoryCustomImpl.java
  src/main/java/com/sparta/ticketauction/domain/goods/response/GoodsAuctionSeatInfoResponse.java
  src/main/java/com/sparta/ticketauction/domain/goods/response/GoodsSeatInfoResponse.java
  src/main/java/com/sparta/ticketauction/domain/goods/service/GoodsService.java
  src/main/java/com/sparta/ticketauction/domain/goods/service/GoodsServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/reservation/controller/ReservationController.java
  src/main/java/com/sparta/ticketauction/domain/reservation/repository/ReservationQueryRepositoryImpl.java
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/repository/ReservationSeatQueryRepository.java
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/repository/ReservationSeatQueryRepositoryImpl.java
  src/main/java/com/sparta/ticketauction/domain/reservation/service/ReservationServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/seat/response/AuctionSeatInfoResponse.java
  src/main/java/com/sparta/ticketauction/domain/seat/response/ReservedSeatResponse.java
  src/main/java/com/sparta/ticketauction/domain/seat/response/SeatInfoResponse.java
  src/main/java/com/sparta/ticketauction/global/config/WebMvcConfig.java
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/ticketauction/global/response/SuccessCode.java
  src/main/resources/static/css/goods-reserve.css
  src/main/resources/static/css/jquery.seat-charts.css
  src/main/resources/static/goods/goods-details.html
  src/main/resources/static/js/basic.js
  src/main/resources/static/js/goods-details.js
  src/main/resources/static/js/jquery-3.7.1.min.js
  src/main/resources/static/js/jquery.seat-charts.js
  src/main/resources/static/reservation/goods_reserve.html
Labels: 🐛 bugfix, ♻️ refactor, ✨ update, 🩹 fix, 🚚 move, 🔥 del, 💄 style

#234 #227 my auction bid view
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
  src/main/resources/static/js/basic.js
  src/main/resources/static/reservation/reservation-list.html
Labels: 🩹 fix

#235 #227 [배포관련] cors 설정 코드
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
Labels: 🐛 bugfix

#236 [global-redis] cluster 설정
  src/main/java/com/sparta/ticketauction/global/config/RedisConfig.java
Labels: 🩹 fix

#237 URL 의 배포 도메인 설정 수정
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
  src/main/resources/static/admin/auction.html
  src/main/resources/static/admin/goods-info.html
  src/main/resources/static/admin/goods.html
  src/main/resources/static/admin/grade.html
  src/main/resources/static/admin/place.html
  src/main/resources/static/admin/zone-grade.html
  src/main/resources/static/auction/auction-list.html
  src/main/resources/static/auction/bid-list.html
  src/main/resources/static/goods/goods-details.html
  src/main/resources/static/header.html
  src/main/resources/static/index.html
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/auction.js
  src/main/resources/static/js/basic.js
  src/main/resources/static/js/common-menu.js
  src/main/resources/static/js/goods-details.js
  src/main/resources/static/js/goods.js
  src/main/resources/static/js/payment.js
  src/main/resources/static/js/reservation.js
  src/main/resources/static/js/signup.js
  src/main/resources/static/js/token.js
  src/main/resources/static/login.html
  src/main/resources/static/payment/fail.html
  src/main/resources/static/payment/request.html
  src/main/resources/static/payment/success.html
  src/main/resources/static/reservation/goods_reserve.html
  src/main/resources/static/reservation/qr.html
  src/main/resources/static/reservation/reservation-detail.html
  src/main/resources/static/reservation/reservation-list.html
  src/main/resources/static/user/common-menu.html
  src/main/resources/static/user/info.html
  src/main/resources/static/user/point-charge-list.html
  src/main/resources/static/user/point-list.html
  src/main/resources/static/user/signup.html
  src/main/resources/static/user/update-info.html
  src/main/resources/static/user/update-pw.html
  src/main/resources/static/user/withdraw.html
Labels: 🐛 bugfix

#238 쿠키 도메인 설저 제거
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
Labels: 🐛 bugfix

#239 [데이터, 좌석 예매] SQL 테스트용 데이터 설정 및 좌석 예매 화면 버그 수정
  src/main/resources/initdata.sql
  src/main/resources/static/reservation/goods_reserve.html
Labels: 🐛 bugfix, 🍻 test

#240 Update data.sql
  src/main/resources/data.sql
Labels: 🙈 docs

#241 [global-redis] cluster 설정
  src/main/java/com/sparta/ticketauction/global/config/RedisConfig.java
Labels: ✨ update

#242 jwt 리프레시 토큰 쿠키에 저장 시, 도메인 설정해주도록 수정(배포환경에서 테스트해봐야함)
  src/main/java/com/sparta/ticketauction/domain/goods/response/GoodsGetResponse.java
  src/main/java/com/sparta/ticketauction/domain/user/response/PointChargeResponse.java
  src/main/java/com/sparta/ticketauction/domain/user/response/PointResponse.java
  src/main/java/com/sparta/ticketauction/domain/user/service/impl/AuthServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
  src/main/java/com/sparta/ticketauction/global/util/UrlUtil.java
Labels: 🩹 fix

#244 배포, 로컬 환경에 따라 변경되도록 수정
  src/main/java/com/sparta/ticketauction/domain/user/service/impl/AuthServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/config/RedisConfig.java
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
  src/main/resources/application.yml
  src/main/resources/static/index.html
Labels: 🐛 bugfix, 🩹 fix

#246 확인을 위해 쿠키에 도메인 세팅 제거
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
Labels: 🔥 del

#247 fix: 확인을 위해 쿠키에 도메인 세팅 추가
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
Labels: 🐛 bugfix

#249 토큰 쿠키로 가져오기 위해 설정 변겅
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
Labels: 🐛 bugfix

#252 토큰 쿠키로 가져오기 위해 설정 변겅
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
Labels: 🐛 bugfix

#253 토큰 쿠키로 가져오기 위해 설정 변겅
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
Labels: 🐛 bugfix

#254 bugfix: 토큰 쿠키로 가져오기 위해 설정 변겅
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
Labels: 🐛 bugfix

#255 토큰 쿠키로 가져오기 위해 설정 변겅
  src/main/java/com/sparta/ticketauction/global/jwt/JwtAuthenticationFilter.java
Labels: 🐛 bugfix

#256 토큰 쿠키로 가져오기 위해 설정 변겅
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
Labels: 🐛 bugfix

#259 토큰 쿠키로 가져오기 위해 설정 변겅 final
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
Labels: 🐛 bugfix

#260 토큰 쿠키로 가져오기 위해 설정 변겅
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
Labels: 🐛 bugfix

#261 엑세스 토큰 만료 시간 및 기본 css 1차 수정
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
  src/main/resources/application-prod.yml
  src/main/resources/static/css/goods-details.css
  src/main/resources/static/css/style.css
  src/main/resources/static/goods/goods-details.html
  src/main/resources/static/header.html
  src/main/resources/static/js/basic.js
  src/main/resources/static/js/goods-details.js
  src/main/resources/static/js/goods.js
  src/main/resources/static/js/token.js
Labels: 🩹 fix

#263 #262 [auction] 경매 정보조회 응답 변경
  src/main/java/com/sparta/ticketauction/domain/auction/response/AuctionDetailResponse.java
  src/main/java/com/sparta/ticketauction/domain/auction/service/AuctionServiceImpl.java
Labels: 🩹 fix

#267 #266 [입찰] 입찰하기 입찰 상태 추가
  src/main/java/com/sparta/ticketauction/domain/auction/repository/AuctionRepositoryCustom.java
  src/main/java/com/sparta/ticketauction/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/com/sparta/ticketauction/domain/auction/service/AuctionServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/bid/constant/BidStatus.java
  src/main/java/com/sparta/ticketauction/domain/bid/entity/Bid.java
  src/main/java/com/sparta/ticketauction/domain/bid/service/BidServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/config/RedisConfig.java
  src/main/java/com/sparta/ticketauction/global/exception/ErrorCode.java
Labels: ✨ update

#273 [bugfix-redis] Redis 설정 수정
  src/main/java/com/sparta/ticketauction/global/config/RedisConfig.java
Labels: 🐛 bugfix

#272 # [update] 좌석 예매 화면 ui 개선
  src/main/resources/static/js/goods-reserve.js
  src/main/resources/static/reservation/goods_reserve.html
Labels: ✨ update

#275 [infra-cicd] CodeDelpoy 배포그룹 변경
  .github/workflows/cicd.yml
Labels: 🩹 fix, 🔨script

#276 [CICD] appspec.yml 수정
  appspec.yml
Labels: 🩹 fix

#274 #270 메인페이지 내에 공연 리스트 노출 커서 기반 페이징으로 전체 출력되도록 하기
  src/main/java/com/sparta/ticketauction/domain/auction/response/AuctionInfoResponse.java
  src/main/java/com/sparta/ticketauction/domain/bid/response/BidInfoResponse.java
  src/main/java/com/sparta/ticketauction/domain/reservation/response/ReservationDetailResponse.java
  src/main/java/com/sparta/ticketauction/domain/reservation/response/ReservationResponse.java
  src/main/java/com/sparta/ticketauction/domain/user/response/PointChargeResponse.java
  src/main/java/com/sparta/ticketauction/domain/user/response/PointResponse.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
  src/main/resources/static/css/style.css
  src/main/resources/static/index.html
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/auction.js
  src/main/resources/static/js/basic.js
  src/main/resources/static/js/common-menu.js
  src/main/resources/static/js/goods-details.js
  src/main/resources/static/js/goods.js
  src/main/resources/static/js/payment.js
  src/main/resources/static/js/reservation.js
  src/main/resources/static/js/signup.js
  src/main/resources/static/js/token.js
Labels: 🩹 fix

#277 [fix-bid] sse 수정
  src/main/java/com/sparta/ticketauction/domain/bid/service/BidServiceImpl.java
Labels: 🩹 fix

#278 css, html 수정 & 예약 취소 기능 프론트 내 구현
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
  src/main/resources/application.yml
  src/main/resources/static/admin/place.html
  src/main/resources/static/css/goods-details.css
  src/main/resources/static/css/mypage.css
  src/main/resources/static/css/nprogress.css
  src/main/resources/static/css/user-input.css
  src/main/resources/static/goods/goods-details.html
  src/main/resources/static/header.html
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/auction.js
  src/main/resources/static/js/basic.js
  src/main/resources/static/js/goods-details.js
  src/main/resources/static/js/goods-reserve.js
  src/main/resources/static/js/goods.js
  src/main/resources/static/js/reservation.js
  src/main/resources/static/js/signup.js
  src/main/resources/static/login.html
  src/main/resources/static/payment/request.html
  src/main/resources/static/reservation/goods_reserve.html
  src/main/resources/static/reservation/reservation-detail.html
  src/main/resources/static/reservation/reservation-list.html
  src/main/resources/static/user/common-menu.html
  src/main/resources/static/user/info.html
  src/main/resources/static/user/point-charge-list.html
  src/main/resources/static/user/point-list.html
  src/main/resources/static/user/signup.html
  src/main/resources/static/user/update-info.html
  src/main/resources/static/user/update-pw.html
Labels: 🩹 fix, 💄 style

#280 Bugfix/#279 예약 취소 오류 수정 및 예약 정보에 가격 추가
  src/main/java/com/sparta/ticketauction/domain/reservation/repository/ReservationQueryRepositoryImpl.java
  src/main/java/com/sparta/ticketauction/domain/reservation/response/ReservationDetailResponse.java
  src/main/java/com/sparta/ticketauction/domain/reservation/response/ReservationResponse.java
  src/main/java/com/sparta/ticketauction/domain/reservation/service/ReservationServiceImpl.java
  src/main/resources/static/js/goods-reserve.js
Labels: 🐛 bugfix

#281 #270 쿠키 설정 변경
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
Labels: 🩹 fix

#282 리프레시 토큰 로컬스토리지로 변경, 인증번호 남은 시간 버그 수정
  src/main/java/com/sparta/ticketauction/domain/user/service/impl/AuthServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/ticketauction/global/jwt/JwtUtil.java
  src/main/resources/static/index.html
  src/main/resources/static/js/basic.js
  src/main/resources/static/js/common-menu.js
  src/main/resources/static/js/goods-reserve.js
  src/main/resources/static/js/goods.js
  src/main/resources/static/js/reservation.js
  src/main/resources/static/js/signup.js
  src/main/resources/static/js/token.js
Labels: 🐛 bugfix

#283 hotfix: 빠진 괄호 추가
  src/main/resources/static/js/goods-reserve.js
Labels: 🐛 bugfix

#285 [인프라] actuator 설정 추가
  build.gradle
  src/main/java/com/sparta/ticketauction/global/config/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: ✨ update

#286 [init-global] logback 설정
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: ✨ update, 🎉 init
