Repository jshstar/ticket-auction-backend, pull requests merged in 2024-02, with the labels that each got.

#287 [인프라] CICD 수정 - log volum 설정 추가
  .github/workflows/cicd.yml
Labels: ✨ update

#289 #288 [goods] 공연 전체 조회 캐싱 생성, 삭제 구현
  src/main/java/com/sparta/ticketauction/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/goods/response/GoodsCategoryGetResponse.java
  src/main/java/com/sparta/ticketauction/domain/goods/response/GoodsGetCursorResponse.java
  src/main/java/com/sparta/ticketauction/domain/goods/response/GoodsGetQueryResponse.java
  src/main/java/com/sparta/ticketauction/domain/goods/response/GoodsResponse.java
  src/main/java/com/sparta/ticketauction/domain/goods/service/GoodsService.java
  src/main/java/com/sparta/ticketauction/domain/goods/service/GoodsServiceImpl.java
  src/main/java/com/sparta/ticketauction/global/config/RedisConfig.java
Labels: ✨ update

#290 # [fix-reservation] 예매 관련 N+1 문제 해결 및 검증 코드 추가, 조회 API 캐시 사용
  src/main/java/com/sparta/ticketauction/domain/auction/repository/AuctionRepositoryCustom.java
  src/main/java/com/sparta/ticketauction/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/com/sparta/ticketauction/domain/goods/controller/GoodsController.java
  src/main/java/com/sparta/ticketauction/domain/reservation/repository/ReservationQueryRepositoryImpl.java
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/repository/ReservationSeatQueryRepository.java
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/repository/ReservationSeatQueryRepositoryImpl.java
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/service/ReservationSeatService.java
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/service/ReservationSeatServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/reservation/service/ReservationServiceImpl.java
Labels: 🐛 bugfix, 🩹 fix

#291 # [fix-reservation] 예약된 좌석 캐시 워밍업 데이터 분할 조회로 변경
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/repository/ReservationSeatQueryRepository.java
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/repository/ReservationSeatQueryRepositoryImpl.java
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/repository/ReservationSeatRepository.java
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/service/ReservationSeatServiceImpl.java
Labels: 🩹 fix

#292 # [fix-reservation] 좌석 예매할 때 구역정보 캐시에 추가하도록 수정
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/service/ReservationSeatServiceImpl.java
  src/main/java/com/sparta/ticketauction/domain/reservation/service/ReservationServiceImpl.java
Labels: 🐛 bugfix

#293 Fix/#284 reservation 좌석 상태 워밍업 분할 로딩 사이즈 5천으로 수정
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/service/ReservationSeatServiceImpl.java
Labels: 🩹 fix

#294 # [fix-reservation] 좌석 상태 워밍업 분할 로딩 사이즈 1천, pipeline 안쓰도록 변경
  src/main/java/com/sparta/ticketauction/domain/reservation/reservation_seat/service/ReservationSeatServiceImpl.java
Labels: 🩹 fix

#295 [cicd] 컨테이너 타임존 변경
  .github/workflows/cicd.yml
Labels: 🩹 fix

#297 Update README.md
  README.md
Labels: 🙈 docs

#299 [CI/CD] workflow 트리거 수정
  .github/workflows/cicd.yml
Labels: 🙈 docs
